param(
    [int]$CommitCount = 30,
    [string]$AuthorContains = "",
    [string]$Since = "",
    [string]$PathFilter = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$outputDir = Join-Path $root "audit-logs"
$outputFile = Join-Path $outputDir "full-audit-log-$timestamp.md"

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$builder = New-Object System.Text.StringBuilder
$bt = [char]96

function Add-Line {
    param([string]$Text = "")
    [void]$builder.AppendLine($Text)
}

function Add-CommandSection {
    param(
        [string]$Title,
        [string]$Workdir,
        [string]$Command
    )
    Add-Line "### $Title"
    Add-Line ""
    Add-Line ("- Directory: " + $bt + $Workdir + $bt)
    Add-Line ("- Command: " + $bt + $Command + $bt)
    Add-Line ""

    $start = Get-Date
    Add-Line "- Start: $($start.ToString('yyyy-MM-dd HH:mm:ss zzz'))"
    Add-Line ""
    Add-Line '```text'
    try {
        Push-Location $Workdir
        Invoke-Expression $Command 2>&1 | ForEach-Object { Add-Line "$_" }
        $exitCode = $LASTEXITCODE
        if ($null -eq $exitCode) { $exitCode = 0 }
    } catch {
        Add-Line "ERROR: $($_.Exception.Message)"
        $exitCode = 1
    } finally {
        Pop-Location
    }
    Add-Line '```'
    $end = Get-Date
    Add-Line ""
    Add-Line "- End: $($end.ToString('yyyy-MM-dd HH:mm:ss zzz'))"
    Add-Line "- Exit Code: $exitCode"
    Add-Line ""
}

Add-Line "# Full Audit Log"
Add-Line ""
Add-Line "## Metadata"
Add-Line ""
Add-Line "- Generated At: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
Add-Line "- Generated By: $env:USERNAME"
Add-Line "- Machine: $env:COMPUTERNAME"
Add-Line ("- Root: " + $bt + $root + $bt)
Add-Line ""

Add-Line "## NPM Audit Output"
Add-Line ""
Add-CommandSection -Title "Root Audit" -Workdir $root -Command "npm audit"
Add-CommandSection -Title "Client Audit" -Workdir (Join-Path $root "client") -Command "npm audit"
Add-CommandSection -Title "Server Audit" -Workdir (Join-Path $root "server") -Command "npm audit"

Add-Line "## Code Change History"
Add-Line ""
Add-Line "- Commit Count: $CommitCount"
if ($AuthorContains) { Add-Line "- Author Filter: $AuthorContains" }
if ($Since) { Add-Line "- Since: $Since" }
if ($PathFilter) { Add-Line "- Path Filter: $PathFilter" }
Add-Line ""
Add-Line '```text'
try {
    $changeScript = Join-Path $PSScriptRoot "change-report.ps1"
    $args = @("-ExecutionPolicy", "Bypass", "-File", "`"$changeScript`"", "-Count", "$CommitCount")
    if ($AuthorContains) { $args += @("-AuthorContains", "`"$AuthorContains`"") }
    if ($Since) { $args += @("-Since", "`"$Since`"") }
    if ($PathFilter) { $args += @("-Path", "`"$PathFilter`"") }

    $cmd = "powershell " + ($args -join " ")
    Invoke-Expression $cmd 2>&1 | ForEach-Object { Add-Line "$_" }
} catch {
    Add-Line "ERROR: $($_.Exception.Message)"
}
Add-Line '```'
Add-Line ""

$builder.ToString() | Out-File -FilePath $outputFile -Encoding utf8
Write-Output "Full audit log generated: $outputFile"
